myproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home'),
    path('about/', views.about, name='about'),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls'))
]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name='list'),
    path('new-post/', views.post_new, name='new-post'),
    path('<slug:slug>', views.post_page, name='page'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    id = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=100)
    content = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    
    def __str__(self):
        return self.title
    
    

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

# Create your models here.
class CustomUserManager(BaseUserManager):
    def create_user(self, username, password=None, **extra_fields):
        if not username:
            raise ValueError('The username field must be set')
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user 

class Users(AbstractBaseUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=40, unique=True)
    email = models.EmailField(max_length = 254)
    password = models.CharField(max_length=128)
    confirm_password = models.CharField(max_length=128, blank=True, null=True)
    
    objects = CustomUserManager()
    
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'email', 'username', 'password', 'confirm_password']
    
    def __str__(self):
        return self.username
    
    

posts/forms.py
from django import forms 
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'content', 'slug', 'banner']

myproject/views.py
# from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('Hello World! I\'m Home.')
    return render(request, 'home.html')

def about(request):
    # return HttpResponse('Hello World! I\'m About.')
    return render(request, 'about.html')

posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms 

# Create your views here.
def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    context = {
        'posts': posts,
    }
    return render(request, 'posts/posts_list.html', context=context)


def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    context = {
        'post': post
    }
    return render(request, 'posts/post_page.html', context=context)

@login_required(login_url='/users/login/')
def post_new(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            # save with user
            newpost = form.save(commit=False)
            newpost.author = request.user
            newpost.save()
            return redirect('posts:list')
    else:
        form = forms.CreatePost()
    return render(request, 'posts/post_new.html', { 'form' : form })

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect('posts:list')
    else:
        form = UserCreationForm()
    return render(request, 'users/register.html', { "form": form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                else:
                    return redirect('posts:list')
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', { 'form' : form })


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/')
    
    return render(request, 'users/logout.html')

posts/templates/posts/post_new.html
{% extends "layout.html" %} 

{% block title %} New Post {% endblock %} 

{% block content %}
<section>
  <h1>New Post</h1>
  <form
    class="form-with-validation"
    action="{% url 'posts:new-post' %}"
    method="post"
    enctype="multipart/form-data"
  >
    {% csrf_token %}
    {{ form }}
    <button class="form-submit" type="submit">Add Post</button>
</form>
</section>
{% endblock %}

posts/templates/posts/post_page.html
{% extends "layout.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <article>
        <img src="{{ post.banner.url }}" title="{{ post.title }}" alt="banner" class="banner" />
        <h1>
            {{ post.title }}
        </h1>
        <p>
            {{ post.content }}
            <br>
            <time>{{ post.date }}</time>
        </p>
    </article>
{% endblock %}

posts/templates/posts/posts_list.html
{% extends 'layout.html' %}
{% block title %}Posts List{% endblock %}
{% block content %}
    <section>
        <h1>Posts List</h1>

        {% for post in posts %}
            <div class="wrapper">
                <div class="card">
                    <h3 class="card-title">{{ post.title }}</h3>
                    <p class="card-content">{{ post.content }} <br> by {{ post.author }}</p>
                    <button class="card-btn"><a href="{% url 'posts:page' slug=post.slug %}">READ MORE</a></button>
                </div>
            </div>
        {% endfor %}
    </section>
{% endblock %}

templates/about.html
{% extends 'layout.html' %}
{% block title %}About{% endblock %}
{% block content %}
    <h1>About</h1>
    <p>This is the about page.</p>
    <p>It is a simple page that provides information about the website.</p>
{% endblock %}

templates/home.html
{% extends 'layout.html' %}
{% block title %}Home{% endblock %}
{% block content %}
    <h1>Welcome to my website!</h1>
    <p>This is the home page.</p>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Django App{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header>
        <nav>
            <a href="/">
                <span role='img' aria-label='Home' title='Home'>🏠</span>
            </a>
            <a href="/about">
                <span role='img' aria-label='About' title='About'>😀</span>
            </a> 
            <a href="{% url 'posts:list' %}">
                <span role='img' aria-label='Posts' title='Posts'>📰</span>
            </a>
            {% if user.is_authenticated %}
                <a href="{% url 'posts:new-post' %}">
                    <span role="img" aria-label="New Post" title="New Post">🆕</span>
                </a>
                <a href="{% url 'users:logout' %}">
                    <span role='img' aria-label='Logout' title='Logout'>🚪</span>
                </a>
            {% else %}
                <a href="{% url 'users:register' %}">
                    <span role='img' aria-label='Registration' title='Registration'>🚀</span>
                </a>
                <a href="{% url 'users:login' %}">
                    <span role='img' aria-label='Login' title='Login'>🌊</span>
                </a>
            {% endif %}
        </nav>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

users/templates/users/login.html
{% extends "layout.html" %}
{% block title %}Login{% endblock %}
{% block content %}
    <h1>Login</h1>
    <form class="form-with-validation" action="/users/login/" method='post'>
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type='hidden' name='next' value='{{ request.GET.next }}' />
        {% endif %}
        <button class="form-submit">Login</button>
    </form>
{% endblock %}

users/templates/users/logout.html
{% extends "layout.html" %}
{% block title %}Logout{% endblock %}
{% block content %}
<form class="logout" action="{% url 'users:logout' %}" method="post">
  {% csrf_token %}
  <button class="logout-button">
    Logout
  </button>
</form>
{% endblock %}

users/templates/users/register.html
{% extends "layout.html" %}
{% block title %}Register{% endblock %}
{% block content %}
    <h1>Register a New User</h1>
    <form class="form-with-validation" action="{% url 'users:register' %}" method='post'>
        {% csrf_token %}
        {{ form }}
        <button class="form-submit">Submit</button>
    </form>
{% endblock %}